-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 16:04:27 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema_inscripcion_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_inscripcion_bd` ;

-- -----------------------------------------------------
-- Schema sistema_inscripcion_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_inscripcion_bd` DEFAULT CHARACTER SET utf8 ;
USE `sistema_inscripcion_bd` ;

-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`persona` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`perfil` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `tipoPerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `persona_idPersona` INT NOT NULL,
  `perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_persona_idx` (`persona_idPersona` ASC),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idPerfil` ASC),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `sistema_inscripcion_bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idPerfil`)
    REFERENCES `sistema_inscripcion_bd`.`perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`alumno` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_alumno_persona1_idx` (`persona_idPersona` ASC),
  CONSTRAINT `fk_alumno_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `sistema_inscripcion_bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`profesor` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `fk_profesor_persona1_idx` (`persona_idPersona` ASC),
  CONSTRAINT `fk_profesor_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `sistema_inscripcion_bd`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`curso` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombreCurso` VARCHAR(45) NOT NULL,
  `profesor_idProfesor` INT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_curso_profesor1_idx` (`profesor_idProfesor` ASC),
  CONSTRAINT `fk_curso_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `sistema_inscripcion_bd`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`inscripcion` (
  `idInscripcion` INT NOT NULL AUTO_INCREMENT,
  `costo` DOUBLE NOT NULL,
  `alumno_idAlumno` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idInscripcion`),
  INDEX `fk_inscripcion_alumno1_idx` (`alumno_idAlumno` ASC),
  INDEX `fk_inscripcion_usuario1_idx` (`usuario_idUsuario` ASC),
  INDEX `fk_inscripcion_curso1_idx` (`curso_idCurso` ASC),
  CONSTRAINT `fk_inscripcion_alumno1`
    FOREIGN KEY (`alumno_idAlumno`)
    REFERENCES `sistema_inscripcion_bd`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `sistema_inscripcion_bd`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `sistema_inscripcion_bd`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`salon` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`salon` (
  `idSalon` INT NOT NULL AUTO_INCREMENT,
  `bloque` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`idSalon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`hora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`hora` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`hora` (
  `idHora` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `horaFinal` TIME NOT NULL,
  PRIMARY KEY (`idHora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`dia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`dia` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`dia` (
  `idDia` INT NOT NULL AUTO_INCREMENT,
  `nombreDia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_inscripcion_bd`.`seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_inscripcion_bd`.`seccion` ;

CREATE TABLE IF NOT EXISTS `sistema_inscripcion_bd`.`seccion` (
  `idSeccion` INT NOT NULL AUTO_INCREMENT,
  `codigoSeccion` VARCHAR(45) NOT NULL,
  `curso_idCurso` INT NOT NULL,
  `salon_idSalon` INT NOT NULL,
  `hora_idHora` INT NOT NULL,
  `dia_idDia` INT NOT NULL,
  PRIMARY KEY (`idSeccion`),
  INDEX `fk_seccion_curso1_idx` (`curso_idCurso` ASC),
  INDEX `fk_seccion_salon1_idx` (`salon_idSalon` ASC),
  INDEX `fk_seccion_hora1_idx` (`hora_idHora` ASC),
  INDEX `fk_seccion_dia1_idx` (`dia_idDia` ASC),
  CONSTRAINT `fk_seccion_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `sistema_inscripcion_bd`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_salon1`
    FOREIGN KEY (`salon_idSalon`)
    REFERENCES `sistema_inscripcion_bd`.`salon` (`idSalon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_hora1`
    FOREIGN KEY (`hora_idHora`)
    REFERENCES `sistema_inscripcion_bd`.`hora` (`idHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_dia1`
    FOREIGN KEY (`dia_idDia`)
    REFERENCES `sistema_inscripcion_bd`.`dia` (`idDia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sistema_inscripcion_bd`.`perfil`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_inscripcion_bd`;
INSERT INTO `sistema_inscripcion_bd`.`perfil` (`idPerfil`, `tipoPerfil`) VALUES (1, 'Super Usuario');
INSERT INTO `sistema_inscripcion_bd`.`perfil` (`idPerfil`, `tipoPerfil`) VALUES (2, 'Usuario');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sistema_inscripcion_bd`.`curso`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_inscripcion_bd`;
INSERT INTO `sistema_inscripcion_bd`.`curso` (`idCurso`, `nombreCurso`, `profesor_idProfesor`) VALUES (1, 'CCNA I', NULL);
INSERT INTO `sistema_inscripcion_bd`.`curso` (`idCurso`, `nombreCurso`, `profesor_idProfesor`) VALUES (2, 'CCNA II', NULL);
INSERT INTO `sistema_inscripcion_bd`.`curso` (`idCurso`, `nombreCurso`, `profesor_idProfesor`) VALUES (3, 'CCNA III', NULL);
INSERT INTO `sistema_inscripcion_bd`.`curso` (`idCurso`, `nombreCurso`, `profesor_idProfesor`) VALUES (4, 'CCNA IV', NULL);
INSERT INTO `sistema_inscripcion_bd`.`curso` (`idCurso`, `nombreCurso`, `profesor_idProfesor`) VALUES (5, 'IT Essential', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sistema_inscripcion_bd`.`salon`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_inscripcion_bd`;
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (1, 'G', '1', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (2, 'G', '2', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (3, 'G', '3', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (4, 'G', '4', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (5, 'G', '5', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (6, 'G', '6', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (7, 'G', '7', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (8, 'G', '8', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (9, 'G', '9', 20);
INSERT INTO `sistema_inscripcion_bd`.`salon` (`idSalon`, `bloque`, `numero`, `capacidad`) VALUES (10, 'G', '10', 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sistema_inscripcion_bd`.`hora`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_inscripcion_bd`;
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (1, '07:00:00', '09:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (2, '09:00:00', '11:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (3, '11:00:00', '13:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (4, '13:00:00', '15:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (5, '15:00:00', '17:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (6, '17:00:00', '19:00:00');
INSERT INTO `sistema_inscripcion_bd`.`hora` (`idHora`, `horaInicio`, `horaFinal`) VALUES (7, '19:00:00', '21:00:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sistema_inscripcion_bd`.`dia`
-- -----------------------------------------------------
START TRANSACTION;
USE `sistema_inscripcion_bd`;
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (1, 'Lunes');
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (2, 'Martes');
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (3, 'Miercoles');
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (4, 'Jueves');
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (5, 'Viernes');
INSERT INTO `sistema_inscripcion_bd`.`dia` (`idDia`, `nombreDia`) VALUES (6, 'Sabado');

COMMIT;

